"""Add SKU discount and active status to Product

Revision ID: 43fa36d29a87
Revises: 85e7aa87887a
Create Date: 2026-08-06 22:08:43.549867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fa36d29a87'
down_revision = '85e7aa87887a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False,server_default=sa.true()))
        batch_op.create_unique_constraint(
           "uq_products_sku",
            ["sku"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_products_sku",
            type_="unique"
        )
        batch_op.drop_column('is_active')
        batch_op.drop_column('discount')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
